### ISSUE TITLE
 undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by joydashy** [KentaaNL/tikkie-api#1]
Hi there,

I am testing this API lib, and running into this error when trying the example code:

```
/var/lib/gems/2.3.0/gems/tikkie-api-0.2.1/lib/tikkie/api/responses/user.rb:29:in `bank_accounts': undefined method `each' for nil:NilClass (NoMethodError)
        from tikkie.rb:26:in `<main>'
```

**Comment by ppostma** [comment]
Hi!

The example code does not do any error checking. I guess something went wrong when you tried to create a user. You can can check the status after calling an API method with `.success?` or `.error?` and use the method `.errors` to retrieve detailed information about the error.

See also the documentation: https://github.com/KentaaNL/tikkie-api#error-handling

**Comment by joydashy** [comment]
Thanks for the reponse. I suppose I don't really understand what a Tikkie user is, I don't actually need an ABN account to create a Tikkie right?

I get this now:
`[#<Tikkie::Api::Responses::Error:0x0055ddf07b4b60 @data={:code=>"ERR_4001_001", :message=>"The requested resource was not found, or a disallowed method was used.", :reference=>"https://developer.abnamro.com/overview", :traceId=>"c630fbec-16a9-466f-9b1e-2ef044dc72e1", :status=>404, :category=>"NOT_FOUND"}>]`

For code:
```
users = client.users.list("platform_token")

user = client.users.create("platform_token",
  name: "Name",
  phone_number: "06xxxxxxxx",
  iban: "NL47INGxxxxxxxxxx",
  bank_account_label: "ING"
)

if user.success?
  puts "Yay!"
else
  puts user.errors.inspect
end
```

**Comment by ppostma** [comment]
Yes, you do need an ABN AMRO developer account to use the API.

I suggest you read the [Get started documentation](https://developer.abnamro.com/get-started) and the [Tikkie API documentation](https://developer.abnamro.com/api/tikkie-v1/tikkie-api-documentation) in ABN AMRO developer portal to understand how it works and what's needed to successfully use this library to create a Tikkie.

Since this does not appear to be a problem in this library, I'm closing the issue now.
